### ISSUE TITLE
Spinning up without Codespace

### ISSUE THREAD

**Issue by raybeecham** [QryptInc/qrypt-security-quickstarts-cpp#52]
Hello, I wanted to ask how I could spin up without using codespaces I've installed the necessary dependencies, but it doesn't seem to work. Can you guide me as to what you've done after the cloning of the repo. Thanks!

**Comment by raybeecham** [comment]
Additionally, I have tried following the steps on the manually building documentation. They do not work as well.

**Comment by qryptdev** [comment]
Hi @raybeecham

Thanks for raising this issue. We suggest using the provided Dockerfile in `/.devcontainer` for creating a containerized environment that installs all of the dependencies and builds the quickstarts. If you are using VSCode, this can be done quickly with the Dev Containers plugin.

If you are not using the Docker container, could you kindly provide additional details on your OS, OS version and architecture? At this time, we only support Ubuntu 22.04 with amd64 (See https://docs.qrypt.com/sdk/quickstarts/cpp/)

We will work on updating our documentation to add details on how to use the Dockerfile and correcting arm64 to amd64.

**Comment by qryptdev** [comment]
Hi @raybeecham 

The entropy and key generator GUIs you've been working on look great!
With the updated README on how to use the docker image, are you still looking for additional documentation on how to build it outside of docker? Happy to add additional documentation on that process as well.

Thanks!

**Comment by raybeecham** [comment]
good morning @qryptdev,

To be honest, I haven't thought of what to try next. I'll stick with the Docker implementation for now, but any suggestions on what else to tinker with? Thanks!

**Comment by qryptdev** [comment]
Hi @raybeecham 

We have added some additional clarifying notes on building manually without Docker in the same README, and have verified that those instructions work. If you can give that a try and let us know if you run into any specific issues, that would be great!

**Comment by raybeecham** [comment]
@raybeecham 

Works beautifully for me. Thanks!

![image](https://github.com/QryptInc/qrypt-security-quickstarts-cpp/assets/20392385/ae3e6237-0099-4250-b473-8c943c29ee47)

**Comment by qryptdev** [comment]
No problem! Closing this issue out as it is now working.
